---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php packages for Ubuntu and Debian
    apt:
      name: 
      -  apache2
      -  libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install httpd and php packages for Centos
    dnf:
      name: 
      -  httpd
      -  php
      state: latest
      update_cache: yest
    when: ansible_distribution == "CentOS"
